In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from keras.models import Model,Sequential
from keras.layers import Input,Dense,Dropout,Activation
from keras.utils import np_utils
from keras.optimizers import Adam
from keras.preprocessing import image

Using TensorFlow backend.


In [2]:
data = pd.read_csv("./train.csv")
data.head()

ID     crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0   1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1   2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2   4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
3   5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
4   7  0.08829  12.5   7.87     0  0.524  6.012  66.6  5.5605    5  311   

   ptratio   black  lstat  medv  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     18.7  394.63   2.94  33.4  
3     18.7  396.90   5.33  36.2  
4     15.2  395.60  12.43  22.9

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 15 columns):
ID         333 non-null int64
crim       333 non-null float64
zn         333 non-null float64
indus      333 non-null float64
chas       333 non-null int64
nox        333 non-null float64
rm         333 non-null float64
age        333 non-null float64
dis        333 non-null float64
rad        333 non-null int64
tax        333 non-null int64
ptratio    333 non-null float64
black      333 non-null float64
lstat      333 non-null float64
medv       333 non-null float64
dtypes: float64(11), int64(4)
memory usage: 39.1 KB


In [4]:
data = np.array(data)

In [5]:
data.shape

(333, 15)

In [6]:
X_train = data[:,1:-1]
Y_train = data[:,-1:]

In [21]:
Y_train.reshape((333,-1))
print(Y_train.shape,X_train.shape)

(333, 1) (333, 13)


In [8]:
un = np.unique(X_train[:,3])
print(un)

[0. 1.]


In [12]:
#Normalisation

X_train[:,1] = (X_train[:,1]-np.min(X_train[:,1]) )/np.max(X_train[:,1])
print(X_train[:,1])
X_train.shape

[0.18  0.    0.    0.    0.125 0.125 0.125 0.125 0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.75  0.75
 0.    0.    0.    0.    0.    0.    0.    0.21  0.21  0.21  0.75  0.9
 0.85  1.    0.25  0.25  0.25  0.25  0.175 0.8   0.8   0.125 0.125 0.
 0.    0.    0.    0.    0.    0.    0.25  0.25  0.25  0.    0.    0.
 0.    0.    0.    0.    0.28  0.28  0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.45
 0.45  0.45  0.45  0.45  0.6   0.6   0.8   0.95  0.825 0.95  0.95  0.
 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.    0.    0.    0.3   0.3   0.3   0.22
 0.22  0.22  

(333, 13)

In [24]:

X_train[:,0] = (X_train[:,0]-np.min(X_train[:,0]) )/np.max(X_train[:,0])
X_train[:,2] = (X_train[:,2]-np.min(X_train[:,2]) )/np.max(X_train[:,2])
X_train[:,4] = (X_train[:,4]-np.min(X_train[:,4]) )/np.max(X_train[:,4])
X_train[:,5] = (X_train[:,5]-np.min(X_train[:,5]) )/np.max(X_train[:,5])
Y_train[:,] = (Y_train[:,]-np.min(Y_train[:,]) )/np.max(Y_train[:,])

X_train.shape

(333, 13)

In [10]:
print(X_train)

[[6.3200e-03 1.8000e-01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [3.2370e-02 0.0000e+00 2.1800e+00 ... 1.8700e+01 3.9463e+02 2.9400e+00]
 ...
 [4.5270e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 9.0800e+00]
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [11]:

model = Sequential()
model.add(Dense(32, input_dim=(13)))
model.add(Activation('relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(1))

model.add(Activation("sigmoid"))

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 32)                448       
_________________________________________________________________
activation_1 (Activation)    (None, 32)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 65        
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0         
Total params: 2,625
Trainable params: 2,625
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.compile(loss="mse", optimizer="adam", metrics=['accuracy'])

In [29]:
hist =  model.fit(X_train,Y_train,
                  epochs=30, 
                  shuffle=True,  
                  batch_size=32,
                  validation_split=0.20)

Train on 266 samples, validate on 67 samples
Epoch 1/30
266/266 [==============================] - 0s 675us/step - loss: 0.4058 - acc: 0.0000e+00 - val_loss: 0.6211 - val_acc: 0.0000e+00
Epoch 2/30
266/266 [==============================] - 0s 89us/step - loss: 0.4058 - acc: 0.0000e+00 - val_loss: 0.6211 - val_acc: 0.0000e+00
Epoch 3/30
266/266 [==============================] - 0s 59us/step - loss: 0.4058 - acc: 0.0000e+00 - val_loss: 0.6211 - val_acc: 0.0000e+00
Epoch 4/30
266/266 [==============================] - 0s 127us/step - loss: 0.4058 - acc: 0.0000e+00 - val_loss: 0.6211 - val_acc: 0.0000e+00
Epoch 5/30
266/266 [==============================] - 0s 81us/step - loss: 0.4058 - acc: 0.0000e+00 - val_loss: 0.6211 - val_acc: 0.0000e+00
Epoch 6/30
266/266 [==============================] - 0s 86us/step - loss: 0.4058 - acc: 0.0000e+00 - val_loss: 0.6211 - val_acc: 0.0000e+00
Epoch 7/30
266/266 [==============================] - 0s 77us/step - loss: 0.4058 - acc: 0.0000e+00 - val_l