In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
df = pd.read_csv("./Train.csv")


In [2]:
data = np.array(df)

In [3]:
print(data.shape)

(1600, 6)


In [4]:
df.head()

feature_1  feature_2  feature_3  feature_4  feature_5     target
0   0.293416  -0.945599  -0.421105   0.406816   0.525662 -82.154667
1  -0.836084  -0.189228  -0.776403  -1.053831   0.597997 -48.897960
2   0.236425   0.132836  -0.147723   0.699854  -0.187364  77.270371
3   0.175312   0.143194  -0.581111  -0.122107  -1.292168  -2.988581
4  -1.693011   0.542712  -2.798729  -0.686723   1.244077 -37.596722

In [5]:
X , Y = data[:,:-1],data[:,5]
print(X.shape,Y.shape)

(1600, 5) (1600,)


In [6]:
m=X.shape[0]
X0 = np.ones([m,1])
X = np.hstack([X0,X])
print(X)


[[ 1.          0.29341624 -0.94559871 -0.42110515  0.40681602  0.52566183]
 [ 1.         -0.83608408 -0.18922804 -0.77640262 -1.05383124  0.59799685]
 [ 1.          0.23642511  0.13283602 -0.14772298  0.69985396 -0.18736416]
 ...
 [ 1.          1.04417694 -0.89920649  1.73039905 -1.87105676  0.44251965]
 [ 1.         -1.2691729  -0.00505216  1.85766873 -1.08036482  0.73633394]
 [ 1.         -1.88400025 -0.84942743 -1.45227035  0.48861308  1.4595758 ]]


In [7]:
print(X.shape)

(1600, 6)


In [8]:
print(type(Y))

<class 'numpy.ndarray'>


In [9]:
Y =Y.reshape((-1,1))

In [10]:
theta = np.dot(np.linalg.pinv(np.dot(X.T,X)),np.dot(X.T,Y))

In [11]:
print(theta.shape)

(6, 1)


In [12]:
theta = theta.reshape((-1,))
print(theta.shape)
print(theta)


(6,)
[ 4.99096674 29.68187118 92.66247759  8.28062089 44.76773522  2.51916121]


In [13]:
def hypothesis(x,theta):
    y=0
    m = 6
    for i in range(m):
        y += x[i]*theta[i]
    return y

In [14]:
test = pd.read_csv("./Test.csv")

In [15]:
test.head()

feature_1  feature_2  feature_3  feature_4  feature_5
0   1.015254   2.076209  -0.266435  -2.418088  -0.980503
1  -0.375021   0.953185   0.626719   0.704406  -0.355489
2  -1.024452   0.962991  -0.407942  -1.861274   0.455201
3  -2.489841   0.544802   0.601219  -0.607021  -1.314286
4  -0.384675  -0.833624   1.358552  -0.547932   0.411925

In [16]:
x_test = test

In [17]:
x_test.shape

(400, 5)

In [18]:
x_test = np.array(x_test)
print(type(x_test))

<class 'numpy.ndarray'>


In [19]:
m= x_test.shape[0]
X0 = np.ones([m,1])
x_test = np.hstack([X0,x_test])
print(x_test)

[[ 1.00000000e+00  1.01525387e+00  2.07620944e+00 -2.66434820e-01
  -2.41808820e+00 -9.80502790e-01]
 [ 1.00000000e+00 -3.75021204e-01  9.53184528e-01  6.26719138e-01
   7.04405750e-01 -3.55489211e-01]
 [ 1.00000000e+00 -1.02445225e+00  9.62991107e-01 -4.07942004e-01
  -1.86127383e+00  4.55201351e-01]
 ...
 [ 1.00000000e+00  5.54727647e-01  1.76824345e+00 -8.97787210e-01
  -1.19366107e+00  3.40563374e-01]
 [ 1.00000000e+00 -1.62717246e+00  8.56470994e-01 -5.65729519e-04
   6.29386649e-01  4.53382144e-01]
 [ 1.00000000e+00  1.39310499e-01  5.31597186e-01 -8.53107053e-01
   3.16920076e-02  1.71489304e+00]]


In [20]:
print(x_test[1,:])

[ 1.         -0.3750212   0.95318453  0.62671914  0.70440575 -0.35548921]


In [21]:
print(theta)

[ 4.99096674 29.68187118 92.66247759  8.28062089 44.76773522  2.51916121]


In [22]:
y_test = []
for i in range(x_test.shape[0]):
    y_test.append(hypothesis(x_test[i,:],theta))

y_test = np.array(y_test)
y_test.reshape(-1,1)
print(y_test.shape)

(400,)


In [23]:
print(y_test[3])

-43.93689854140082


In [26]:
with open('Sample_Submission.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    m = y_test.shape[0]
    writer.writerow(["Id","Target"])
    for i in range(m):
        l = [i,y_test[i]]
        writer.writerow(l)
    csvFile.close()